### ISSUE TITLE
Could add tooltips with participant names to SVG

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/project_metric_slack#3]
so that mouseover tells you who is most active in heatmap?

**Comment by armandofox** [comment]
this is one reason i originally was thinking in terms of having each metric gem generate a partial as opposed to an svg. A mouseover tooltip is pure HTML/CSS, and a partial could also assume (eg) that jQuery is available to do more sophisticated interactions.  one can envision an API that asks if a particular metric plugin would `respond_to?` some method indicating it can render itself as a partial, and if not, just retrieve the static svg or png.
